### PR TITLE
Add a giphy alias for compat with slack command

### PR DESCRIPTION
**Pull request by patcon**
I'm trying to migrate folks from  the slack integration for giphy, and it would be helpful if that command worked here too :)

### CODE REVIEW

**Comment by patcon** [comment]
Also, I notice that you're not using `grunt-release`. I've found that this make it *super* simple to release even the smallest changes in new tagged npm releases, if you're so inclined to add it.

If you're generating scripts via the official yeoman scaffold generator, then you get it for free :) You can prob use it as a template for this repo:

- https://github.com/github/generator-hubot/blob/master/generators/script/templates/Gruntfile.js#L15-L20
- https://github.com/github/generator-hubot/blob/master/generators/script/templates/_package.json#L34

**Comment by bencentra** [comment]
:+1:

I use neither grunt nor yeoman here, I'll definitely look into it!

**Comment by bencentra** [comment]
Released as v0.1.5

**Comment by patcon** [comment]
Whoop! Thanks!

**Pull request merged**
